AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the ApiGateway::DomainName::SecurityPolicy resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: apigateway_domainname_securitypolicy.handlers.hook
      Runtime: python3.7
      CodeUri: build/

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: apigateway_domainname_securitypolicy.handlers.test_entrypoint
      Runtime: python3.7
      CodeUri: build/

